### PR TITLE
jsonserializer: Treat `all` as a normal subgroup, reserve and use `nrn_all` as list of all segments/sections

### PR DESCRIPTION
**Pull request by sanjayankur31**

### CODE REVIEW

**Comment by pgleeson** [comment]
Failing with other neuron models which implicitly use all, e.g. https://github.com/openworm/hodgkin_huxley_tutorial/tree/master/Tutorial/Source, probably because **all** is not used in the channelDensity (https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/hhcell.cell.nml), but needs to be added/created in the NEURON hoc:
```
>$ python LEMS_HH_SingleAP_nrn.py 

    Starting simulation in NEURON of 50ms generated from NeuroML2 model...

Population hhpop contains 1 instance(s) of component: hhcell of type: cell
	1 
NEURON: syntax error
 in hhcell.hoc near line 94
     forsec all v = -65.0  // units: mV
              ^
        xopen("hhcell.hoc")
      execute1("{xopen("hh...")
    load_file("hhcell.hoc")
Segmentation fault: 11
(py39n) Padraigs-MacBook-Pro-M2:Source padraig$ 

```

**Comment by sanjayankur31** [comment]
We decided to go a different way with a little more intelligence built in:

- reserve the `all` segment group to mean "all segments in the cell".
- if it is defined in the NeuroML representation, run a validation check to ensure that it does contain all segments of the cell; if it doesn't, throw a validation error
- so, users should not be messing with this reserved group
- document that:
  - `all` is reserved and must contain all segments
  - for convenience, `all` is optional---even if it is not explicitly defined in the cell, users can refer to it (or leave it out entirely---and we'll assume they mean `all`.

**Comment by sanjayankur31** [comment]
@pgleeson : updated, got to tweak the validator to check for `all` now.

**Comment by pgleeson** [comment]
Tested and looks good!

**Pull request merged**
